### ISSUE TITLE
Feature request: allow fetching full information in IP lookup

### ISSUE THREAD

**Issue by timedoutuk** [SHRoNK-Corporation/shronk-ip-spec#1]
Currently, there is no way to perform a full lookup (like that seen of `/full`) on an IP via `/lookup`.

This would be nice to have as it would allow fetching information such as remote currencies and timezones.

**Comment by thinkingsand** [comment]
Added with the `/lookup/full` endpoint in https://github.com/SHRoNK-Corporation/shronk-ip/commit/68c07500576a4382224ca63456fdaf013cf7522b
